# Generated by Django 5.0.6 on 2024-06-07 19:34

import django.core.validators
import quizzes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Savol')),
                ('answer_a', models.TextField(verbose_name="A varyant (To'g'ri javob)")),
                ('answer_b', models.TextField(verbose_name='B varyant')),
                ('answer_c', models.TextField(verbose_name='C varyant')),
                ('answer_d', models.TextField(verbose_name='D varyant')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Test nomi')),
                ('passing_score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=100, message='Mksimal qiymat 100'), django.core.validators.MinValueValidator(limit_value=50, message='Minimal qiymat 50')], verbose_name="O'tish bali")),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=100, message='Maksimal savollar soni 100'), django.core.validators.MinValueValidator(limit_value=10, message='Minimal savollar soni 10')], verbose_name='Test savollar soni')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField(editable=False, verbose_name="To'g'ri javoblar soni")),
                ('score', models.DecimalField(decimal_places=2, editable=False, max_digits=100, verbose_name='Ball')),
                ('answers', models.JSONField(default=quizzes.models.default, editable=False)),
                ('status', models.CharField(choices=[('passed', "O'tgan"), ('failed', "O'tmagan")], editable=False, max_length=100, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Natija',
                'verbose_name_plural': 'Natijalar',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="To'plam nomi")),
            ],
            options={
                'verbose_name': "To'plam",
                'verbose_name_plural': "To'plamlar",
            },
        ),
    ]
